//
//  MacOrbitCardView.swift
//  NewtonMac
//
//  Created for Newton macOS.
//

import SwiftUI
import AppKit

public struct MacOrbitCardView: View {
    public let result: OrbitExecutionResult
    
    public init(result: OrbitExecutionResult) {
        self.result = result
    }
    
    public var body: some View {
        if result.orbitName.lowercased() == "generate_pdf" || result.orbitName.lowercased() == "pdf" {
            MacPDFDocumentCardView(result: result)
        } else {
            VStack(alignment: .leading, spacing: 6) {
                HStack {
                    Image(systemName: "circle.circle.fill")
                        .font(.system(size: 11))
                        .foregroundColor(NewtonTheme.forestGreen)
                    
                    Text("Orbit: \(result.orbitName.uppercased())")
                        .font(.system(size: 11, weight: .bold, design: .monospaced))
                        .foregroundColor(NewtonTheme.forestGreen)
                    
                    Spacer()
                    
                    Image(systemName: "checkmark.seal.fill")
                        .font(.system(size: 11))
                        .foregroundColor(NewtonTheme.forestGreen)
                }
                
                Text(result.result)
                    .font(.system(size: 12))
                    .foregroundColor(NewtonTheme.textPrimary)
                    .lineLimit(6)
            }
            .padding(10)
            .background(NewtonTheme.surface.opacity(0.7))
            .clipShape(RoundedRectangle(cornerRadius: 8, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: 8, style: .continuous)
                    .stroke(NewtonTheme.forestGreen.opacity(0.4), lineWidth: 0.8)
            )
        }
    }
}

public struct MacPDFDocumentCardView: View {
    public let result: OrbitExecutionResult
    
    private var pdfUrl: URL? {
        let path = result.result.trimmingCharacters(in: .whitespacesAndNewlines)
        if path.hasPrefix("file://"), let url = URL(string: path) {
            return url
        }
        if FileManager.default.fileExists(atPath: path) {
            return URL(fileURLWithPath: path)
        }
        return nil
    }
    
    private var documentTitle: String {
        if let data = result.params.data(using: .utf8),
           let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
           let title = json["title"] as? String, !title.isEmpty {
            return title
        }
        if let titleRegex = try? NSRegularExpression(pattern: "\"title\"\\s*:\\s*\"([^\"]+)\""),
           let match = titleRegex.firstMatch(in: result.params, range: NSRange(location: 0, length: (result.params as NSString).length)),
           match.numberOfRanges > 1 {
            return (result.params as NSString).substring(with: match.range(at: 1))
        }
        if let pdfUrl = pdfUrl {
            return pdfUrl.deletingPathExtension().lastPathComponent
        }
        return "Documento Newton"
    }
    
    public var body: some View {
        HStack(spacing: 14) {
            // PDF Icon
            ZStack {
                RoundedRectangle(cornerRadius: 8, style: .continuous)
                    .fill(NewtonTheme.coralRed.opacity(0.15))
                    .frame(width: 48, height: 48)
                
                Image(systemName: "doc.richtext.fill")
                    .font(.system(size: 24))
                    .foregroundColor(NewtonTheme.coralRed)
            }
            
            VStack(alignment: .leading, spacing: 3) {
                Text(documentTitle)
                    .font(.system(size: 14, weight: .semibold, design: .serif))
                    .foregroundColor(NewtonTheme.textPrimary)
                    .lineLimit(1)
                
                Text("PDF Document • Generated by Newton")
                    .font(.system(size: 11))
                    .foregroundColor(NewtonTheme.textSecondary)
            }
            
            Spacer()
            
            if let url = pdfUrl {
                // Reveal in Finder / Open in Preview
                Button(action: {
                    NSWorkspace.shared.activateFileViewerSelecting([url])
                }) {
                    HStack(spacing: 4) {
                        Image(systemName: "folder")
                        Text("Show in Finder")
                    }
                    .font(.system(size: 11))
                }
                .buttonStyle(.bordered)
                
                Button(action: {
                    NSWorkspace.shared.open(url)
                }) {
                    HStack(spacing: 4) {
                        Image(systemName: "arrow.up.forward.app")
                        Text("Open")
                    }
                    .font(.system(size: 11, weight: .semibold))
                }
                .buttonStyle(.borderedProminent)
                .tint(NewtonTheme.sand)
            }
        }
        .padding(12)
        .background(NewtonTheme.card)
        .clipShape(RoundedRectangle(cornerRadius: 10, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: 10, style: .continuous)
                .stroke(NewtonTheme.sand.opacity(0.4), lineWidth: 1)
        )
    }
}
