//
//  OrbitCardView.swift
//  Newton
//
//  Created for Newton iOS.
//

import SwiftUI
import QuickLook

public struct OrbitCardView: View {
    public let result: OrbitExecutionResult
    
    public init(result: OrbitExecutionResult) {
        self.result = result
    }
    
    public var body: some View {
        if result.orbitName.lowercased() == "generate_pdf" || result.orbitName.lowercased() == "pdf" {
            PDFDocumentCardView(result: result)
        } else {
            VStack(alignment: .leading, spacing: 6) {
                HStack {
                    Image(systemName: "circle.circle.fill")
                        .font(.system(size: 11))
                        .foregroundColor(NewtonTheme.forestGreen)
                    
                    Text("Orbit: \(result.orbitName.uppercased())")
                        .font(.system(size: 11, weight: .bold, design: .monospaced))
                        .foregroundColor(NewtonTheme.forestGreen)
                    
                    Spacer()
                    
                    Image(systemName: "checkmark.seal.fill")
                        .font(.system(size: 11))
                        .foregroundColor(NewtonTheme.forestGreen)
                }
                
                Text(result.result)
                    .font(.system(size: 12))
                    .foregroundColor(NewtonTheme.textPrimary)
                    .lineLimit(6)
            }
            .padding(10)
            .background(NewtonTheme.surface.opacity(0.7))
            .clipShape(RoundedRectangle(cornerRadius: 10, style: .continuous))
            .overlay(
                RoundedRectangle(cornerRadius: 10, style: .continuous)
                    .stroke(NewtonTheme.forestGreen.opacity(0.4), lineWidth: 0.8)
            )
        }
    }
}

public struct PDFDocumentCardView: View {
    public let result: OrbitExecutionResult
    @State private var shareUrl: URL? = nil
    
    private var pdfUrl: URL? {
        let path = result.result.trimmingCharacters(in: .whitespacesAndNewlines)
        if path.hasPrefix("file://"), let url = URL(string: path) {
            return url
        }
        if FileManager.default.fileExists(atPath: path) {
            return URL(fileURLWithPath: path)
        }
        // Try extracting URL from Markdown link [Title](url)
        if let start = path.range(of: "](")?.upperBound,
           let end = path.range(of: ")", range: start..<path.endIndex)?.lowerBound {
            let extracted = String(path[start..<end])
            if extracted.hasPrefix("file://"), let url = URL(string: extracted) {
                return url
            }
            if FileManager.default.fileExists(atPath: extracted) {
                return URL(fileURLWithPath: extracted)
            }
        }
        return nil
    }
    
    private var documentTitle: String {
        if let data = result.params.data(using: .utf8),
           let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
           let title = json["title"] as? String, !title.isEmpty {
            return title
        }
        if let titleRegex = try? NSRegularExpression(pattern: "\"title\"\\s*:\\s*\"([^\"]+)\""),
           let match = titleRegex.firstMatch(in: result.params, range: NSRange(location: 0, length: (result.params as NSString).length)),
           match.numberOfRanges > 1 {
            return (result.params as NSString).substring(with: match.range(at: 1))
        }
        if let pdfUrl = pdfUrl {
            return pdfUrl.deletingPathExtension().lastPathComponent
        }
        return "Documento Newton"
    }
    
    public var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 12) {
                // PDF Icon Badge
                ZStack {
                    RoundedRectangle(cornerRadius: 10, style: .continuous)
                        .fill(NewtonTheme.coralRed.opacity(0.15))
                        .frame(width: 44, height: 44)
                    
                    Image(systemName: "doc.richtext.fill")
                        .font(.system(size: 22))
                        .foregroundColor(NewtonTheme.coralRed)
                }
                
                VStack(alignment: .leading, spacing: 2) {
                    Text(documentTitle)
                        .font(.system(size: 14, weight: .semibold, design: .serif))
                        .foregroundColor(NewtonTheme.textPrimary)
                        .lineLimit(1)
                    
                    Text("PDF Document • Generated by Newton")
                        .font(.system(size: 11))
                        .foregroundColor(NewtonTheme.textSecondary)
                }
                
                Spacer()
            }
            
            // Action Buttons Bar (Open & Share)
            HStack(spacing: 10) {
                if let url = pdfUrl {
                    // Open / QuickLook View
                    ShareLink(item: url) {
                        HStack(spacing: 6) {
                            Image(systemName: "square.and.arrow.up")
                            Text("Compartir / Guardar")
                        }
                        .font(.system(size: 12, weight: .medium))
                        .foregroundColor(NewtonTheme.sand)
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 8)
                        .background(NewtonTheme.card)
                        .clipShape(RoundedRectangle(cornerRadius: 8, style: .continuous))
                        .overlay(
                            RoundedRectangle(cornerRadius: 8, style: .continuous)
                                .stroke(NewtonTheme.border, lineWidth: 0.8)
                        )
                    }
                }
            }
        }
        .padding(14)
        .background(NewtonTheme.card)
        .clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
        .overlay(
            RoundedRectangle(cornerRadius: 14, style: .continuous)
                .stroke(NewtonTheme.sand.opacity(0.5), lineWidth: 1)
        )
        .padding(.vertical, 4)
    }
}
