//
//  LLMService.swift
//  Newton
//
//  Created for Newton iOS.
//

import Foundation

public enum LLMError: LocalizedError {
    case invalidURL
    case missingApiKey(AIProvider)
    case serverError(statusCode: Int, message: String)
    case decodingError(String)
    case noResponse
    
    public var errorDescription: String? {
        switch self {
        case .invalidURL:
            return "Invalid endpoint URL."
        case .missingApiKey(let provider):
            return "API Key required for \(provider.displayName). Please configure it in Settings."
        case .serverError(let code, let msg):
            return "Server Error (\(code)): \(msg)"
        case .decodingError(let detail):
            return "Failed to parse response: \(detail)"
        case .noResponse:
            return "No response generated by the AI model."
        }
    }
}

public final class LLMService {
    public static let shared = LLMService()
    
    private let session: URLSession
    
    private init() {
        let config = URLSessionConfiguration.default
        config.timeoutIntervalForRequest = 120
        config.timeoutIntervalForResource = 300
        self.session = URLSession(configuration: config)
    }
    
    /// Stream tokens asynchronously from the selected AI Provider
    public func streamCompletion(
        messages: [Message],
        provider: AIProvider,
        modelId: String,
        baseUrl: String,
        apiKey: String,
        temperature: Double = 0.7,
        maxTokens: Int = 2048,
        systemPrompt: String = ""
    ) -> AsyncThrowingStream<String, Error> {
        return AsyncThrowingStream { continuation in
            let task = Task {
                do {
                    guard let url = buildEndpointUrl(provider: provider, baseUrl: baseUrl) else {
                        continuation.finish(throwing: LLMError.invalidURL)
                        return
                    }
                    
                    var request = URLRequest(url: url)
                    request.httpMethod = "POST"
                    request.setValue("application/json", forHTTPHeaderField: "Content-Type")
                    request.setValue("Newton-iOS/1.0", forHTTPHeaderField: "User-Agent")
                    
                    // Attach headers
                    applyHeaders(request: &request, provider: provider, apiKey: apiKey)
                    
                    // Build body payload
                    let bodyData = try buildPayload(
                        messages: messages,
                        provider: provider,
                        modelId: modelId,
                        temperature: temperature,
                        maxTokens: maxTokens,
                        systemPrompt: systemPrompt,
                        stream: true
                    )
                    request.httpBody = bodyData
                    
                    let (asyncBytes, response) = try await session.bytes(for: request)
                    
                    guard let httpResponse = response as? HTTPURLResponse else {
                        continuation.finish(throwing: LLMError.noResponse)
                        return
                    }
                    
                    guard (200...299).contains(httpResponse.statusCode) else {
                        var errorBody = ""
                        for try await line in asyncBytes.lines {
                            errorBody += line
                        }
                        continuation.finish(throwing: LLMError.serverError(statusCode: httpResponse.statusCode, message: errorBody))
                        return
                    }
                    
                    let isAnthropic = provider.isAnthropicProtocol
                    
                    for try await line in asyncBytes.lines {
                        guard !Task.isCancelled else { break }
                        
                        let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
                        guard !trimmed.isEmpty else { continue }
                        
                        if trimmed.hasPrefix("data: ") {
                            let jsonStr = String(trimmed.dropFirst(6)).trimmingCharacters(in: .whitespacesAndNewlines)
                            if jsonStr == "[DONE]" { break }
                            
                            if let data = jsonStr.data(using: .utf8),
                               let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
                                
                                if isAnthropic {
                                    // Parse Anthropic SSE
                                    let type = json["type"] as? String ?? ""
                                    if type == "content_block_delta",
                                       let delta = json["delta"] as? [String: Any],
                                       let text = delta["text"] as? String {
                                        continuation.yield(text)
                                    }
                                } else {
                                    // Parse OpenAI SSE
                                    if let choices = json["choices"] as? [[String: Any]],
                                       let first = choices.first,
                                       let delta = first["delta"] as? [String: Any] {
                                        
                                        if let content = delta["content"] as? String {
                                            continuation.yield(content)
                                        } else if let reasoning = delta["reasoning_content"] as? String {
                                            continuation.yield(reasoning)
                                        }
                                    }
                                }
                            }
                        }
                    }
                    
                    continuation.finish()
                } catch {
                    continuation.finish(throwing: error)
                }
            }
            
            continuation.onTermination = { @Sendable _ in
                task.cancel()
            }
        }
    }
    
    // MARK: - Helpers
    
    private func buildEndpointUrl(provider: AIProvider, baseUrl: String) -> URL? {
        let base = baseUrl.trimmingCharacters(in: CharacterSet(charactersIn: "/"))
        
        switch provider {
        case .anthropic, .anthropicCompatible:
            if base.hasSuffix("/messages") { return URL(string: base) }
            return URL(string: "\(base)/messages")
            
        case .openai, .openrouter, .openaiCompatible, .gemini, .groq, .deepseek, .ollama:
            if base.hasSuffix("/chat/completions") { return URL(string: base) }
            return URL(string: "\(base)/chat/completions")
        }
    }
    
    private func applyHeaders(request: inout URLRequest, provider: AIProvider, apiKey: String) {
        if provider.isAnthropicProtocol {
            if !apiKey.isEmpty {
                request.setValue(apiKey, forHTTPHeaderField: "x-api-key")
            }
            request.setValue("2023-06-01", forHTTPHeaderField: "anthropic-version")
            request.setValue("true", forHTTPHeaderField: "anthropic-dangerous-direct-browser-access")
        } else {
            if !apiKey.isEmpty {
                request.setValue("Bearer \(apiKey)", forHTTPHeaderField: "Authorization")
            }
            if provider == .openrouter {
                request.setValue("https://newton.app", forHTTPHeaderField: "HTTP-Referer")
                request.setValue("Newton iOS", forHTTPHeaderField: "X-Title")
            }
        }
    }
    
    private func buildPayload(
        messages: [Message],
        provider: AIProvider,
        modelId: String,
        temperature: Double,
        maxTokens: Int,
        systemPrompt: String,
        stream: Bool
    ) throws -> Data {
        if provider.isAnthropicProtocol {
            // Anthropic Messages API format
            var anthropicMsgs: [[String: String]] = []
            
            for msg in messages {
                if msg.role == .system { continue }
                let roleStr = (msg.role == .assistant) ? "assistant" : "user"
                let contentStr = msg.content.trimmingCharacters(in: .whitespacesAndNewlines)
                if !contentStr.isEmpty {
                    anthropicMsgs.append(["role": roleStr, "content": contentStr])
                }
            }
            
            if anthropicMsgs.isEmpty {
                anthropicMsgs.append(["role": "user", "content": "Hello"])
            }
            
            var payload: [String: Any] = [
                "model": modelId,
                "messages": anthropicMsgs,
                "max_tokens": maxTokens,
                "temperature": temperature,
                "stream": stream
            ]
            
            if !systemPrompt.isEmpty {
                payload["system"] = systemPrompt
            }
            
            return try JSONSerialization.data(withJSONObject: payload, options: [])
        } else {
            // OpenAI format
            var formattedMessages: [[String: String]] = []
            
            if !systemPrompt.isEmpty {
                formattedMessages.append(["role": "system", "content": systemPrompt])
            }
            
            for msg in messages {
                let roleStr: String
                switch msg.role {
                case .system: roleStr = "system"
                case .assistant: roleStr = "assistant"
                case .user: roleStr = "user"
                }
                let contentStr = msg.content.trimmingCharacters(in: .whitespacesAndNewlines)
                if !contentStr.isEmpty {
                    formattedMessages.append(["role": roleStr, "content": contentStr])
                }
            }
            
            let payload: [String: Any] = [
                "model": modelId,
                "messages": formattedMessages,
                "temperature": temperature,
                "max_tokens": maxTokens,
                "stream": stream
            ]
            
            return try JSONSerialization.data(withJSONObject: payload, options: [])
        }
    }
}
